TrajectoryPlannerROS:
  max_vel_x: 0.4
  min_vel_x: 0.1
  max_vel_theta: 2.5
  min_vel_theta: -2.5
  escape_vel: -0.3
  
  acc_lim_theta: 3.2
  acc_lim_x: 2.5
  acc_lim_y: 2.5

  meter_scoring: true

  holonomic_robot: false

  yaw_goal_tolerance: 0.5
  xy_goal_tolerance: 0.1

  pdist_scale: 0.6          # weighting for how much controller should stay close to the path it was given, maximal possible value is 5.0
  gdist_scale: 0.8          # weighting for how much controller should attempt to reach its local goal, also controls speed, maximal possible value is 5.0
  occdist_scale: 0.01       # weighting for how much controller should attempt to avoid obstacles
