obstacle_range: 10.0
raytrace_range: 15.0
footprint: [[-0.2, 0.25], [0.2, 0.25], [0.2, -0.25], [-0.2, -0.25]]
inflation_radius: 0.5

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: map, data_type: LaserScan, topic: scan, marking: true, clearing: true}
