
# erpm (electrical rpm) = speed_to_erpm_gain * speed (meters / second) + speed_to_erpm_offset
speed_to_erpm_gain: 4614
speed_to_erpm_offset: 0.0

# servo value (0 to 1) =  steering_angle_to_servo_gain * steering angle (radians) + steering_angle_to_servo_offset
steering_angle_to_servo_gain: -1.2135
steering_angle_to_servo_offset: 0.463

# publish odom to base link tf
vesc_to_odom/publish_tf: true

# car wheelbase is about 25cm 
wheelbase: .25

vesc_driver:
  port: /dev/ttyACM0
  duty_cycle_min: -0.5
  duty_cycle_max: 0.5
  current_min: -20.0
  current_max: 20.0
  brake_min: 0.0
  brake_max: 50.0
  speed_min: -6000
  speed_max: 12000
  position_min: 0.0
  position_max: 0.0
  servo_min: 0.1
  servo_max: 0.9
